#a revoir tous les points payload et elastic

# Variables to be set on group / project in gitlab variables:

# CI_DOMAIN
# CI_TOOLS_REPOSITORY_URL
# SENTRY_DSN

workflow:
  # Only run the pipeline if this is the default branch or a MR
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      variables:
        PIPELINE_NAME: "MR pipeline: $CI_COMMIT_BRANCH"
        IS_MR: "true"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      variables:
        PIPELINE_NAME: "default branch pipeline: $CI_COMMIT_BRANCH"
    - if: $CI_COMMIT_BRANCH == "main"
      variables:
        PIPELINE_NAME: "main branch pipeline: $CI_COMMIT_BRANCH"

stages:
  - maintenance
  - lint
  - build
  - refresh
  - migrate
  - review
  - stop_review
  - review_preprod
  - docker_push

before_script:
  - export DOCKER_BUILDKIT=1
  - export TYPESENS_INDEX_PREFIX=ocastore
  - ./bin/extract_mr_variable_env.py
  - cat mr_variable.sh
  - source mr_variable.sh
  - cp .env-ci .env
  - export BUILD_NAME=${CI_PROJECT_NAME/-/_}_${CI_MERGE_REQUEST_IID:-preprod}
  - export CI_DOMAIN=${CI_DOMAIN}
  - |
    if [[ "$CI_MERGE_REQUEST_LABELS" == *"deploy-payload"* ]] || [[ "$CI_COMMIT_BRANCH == 'main'" ]]; then
      export COMPOSE_FILE="ci.docker-compose.yml:payload.docker-compose.yml:ci-payload.docker-compose.yml:secrets.docker-compose.yml"
      export NUXT_PUBLIC_PAYLOAD_URL="https://${CI_PROJECT_NAME}_${CI_MERGE_REQUEST_IID:-preprod}nuxt.ci-akretion.com"
      export NUXT_PAYLOAD_URL="http://payload:1337"
    else
      export COMPOSE_FILE="ci.docker-compose.yml"
      export NUXT_PUBLIC_PAYLOAD_URL="https://akretion.com"
    fi
  - |
    cat << EOF >> .env
    UID=`id -u`
    BUILD_NAME=${BUILD_NAME}
    COMPOSE_FILE=${COMPOSE_FILE}
    COMPOSE_PROJECT_NAME=${BUILD_NAME}
    NUXT_PUBLIC_PAYLOAD_URL=${NUXT_PUBLIC_PAYLOAD_URL}
    NUXT_PAYLOAD_URL=${NUXT_PAYLOAD_URL}
    PGDATABASE=${BUILD_NAME}
    DB_NAME=${BUILD_NAME}
    CI_DOMAIN=${CI_DOMAIN}
    BASE_DOMAIN_NAME=${CI_PROJECT_NAME}_${CI_MERGE_REQUEST_IID:-preprod}
    EOF
  - sops -d secrets.docker-compose.enc.yml > secrets.docker-compose.yml

# Pre-commit lint
# TODO add linter per project
#lint:
#  stage: lint
#  script:
#    - pre-commit install
#    - pre-commit run --all --show-diff-on-failure --verbose --color always
#  allow_failure: true

# Build the container
build:
  stage: build
  script:
    - git submodule init
    - git submodule update
    - docker compose build --pull

# Drop the database to restart from a fresh one
refresh_copy_db:
  stage: refresh
  script:
    - docker compose kill
    - dropdb --force --if-exists $BUILD_NAME
    - createdb $BUILD_NAME -T ${CI_PROJECT_NAME/-/_}_template
  rules:
    # if keepdb tag is set this job will not run
    - if: $CI_MERGE_REQUEST_LABELS !~ /keepdb/ && $CI_MERGE_REQUEST_LABELS =~ /deploy-payload/

# Run the container used for the review
review:
  stage: review
  script:
    - echo "DB_NAME=$BUILD_NAME" >> .env
    - docker compose kill
    - docker compose up -d
  environment:
    name: test/${CI_PROJECT_NAME}_${CI_MERGE_REQUEST_IID}
    url: https://${CI_PROJECT_NAME}_${CI_MERGE_REQUEST_IID}nuxt.${CI_DOMAIN}
    on_stop: stop_review
  rules:
    - if: $IS_MR == "true"

# Stop the container used for the review
stop_review:
  stage: review
  script:
    - docker compose down --rmi local --volumes
    - dropdb ${CI_PROJECT_NAME}_${CI_MERGE_REQUEST_IID} --if-exist
    - dropdb ${CI_PROJECT_NAME}_${CI_MERGE_REQUEST_IID}_test --if-exist
  environment:
    name: test/${CI_PROJECT_NAME}_${CI_MERGE_REQUEST_IID}
    action: stop
  when: manual
  rules:
    - if: $IS_MR == "true"

# Start the preprod container
review_preprod:
  stage: review_preprod
  script:
    - echo "DB_NAME=$BUILD_NAME" >> .env
    - echo "DOMAIN=${CI_PROJECT_NAME}_preprod.${CI_DOMAIN}"
    - echo "DOMAIN=${CI_PROJECT_NAME}_preprod.${CI_DOMAIN}" >> .env
    - docker compose kill
    - docker compose up -d
  environment:
    name: preprod
    url: https://${CI_PROJECT_NAME}_preprodnuxt.${CI_DOMAIN}
  rules:
    - if: $IS_MR == null

# Send the docker image to the registry in order to be downloaded in prod
docker_push:
  stage: docker_push
  script:
    - export TAG="${CI_COMMIT_MESSAGE//Release /}"
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker tag ${BUILD_NAME}_nuxt $CI_REGISTRY_IMAGE/nuxt:latest
    - docker push $CI_REGISTRY_IMAGE/nuxt:latest
    - docker tag ${BUILD_NAME}_nuxt $CI_REGISTRY_IMAGE/nuxt:$TAG
    - docker push $CI_REGISTRY_IMAGE/nuxt:$TAG
    - docker tag ${BUILD_NAME}_payload $CI_REGISTRY_IMAGE/payload:latest
    - docker push $CI_REGISTRY_IMAGE/payload:latest
    - docker tag ${BUILD_NAME}_payload $CI_REGISTRY_IMAGE/payload:$TAG
    - docker push $CI_REGISTRY_IMAGE/payload:$TAG
  rules:
    - if: $CI_COMMIT_TITLE =~ /^Release/ && $IS_MR == null

# Delete the data associated with the stopped containers
# Runs automatically every night
prune_docker:
  stage: maintenance
  script:
    - docker system prune --all --volumes --force
  when: manual
  rules:
    - if: $IS_MR == null
