services:
  nuxt:
    build:
      context: .
    image: '${BUILD_NAME}_nuxt'
    environment:
      NUXT_PUBLIC_SEARCH_URL: https://dev-typesense.akretion.com
      NUXT_PUBLIC_SEARCH_INDICES_COMPANIES_EN: '${TYPESENS_INDEX_PREFIX}_companies'
      NUXT_PUBLIC_SEARCH_INDICES_PERSONS_EN: '${TYPESENS_INDEX_PREFIX}_persons'
      NUXT_PUBLIC_SEARCH_INDICES_MODULES_EN: '${TYPESENS_INDEX_PREFIX}_modules'
      NUXT_PUBLIC_SEARCH_INDICES_CATEGORIES_EN: '${TYPESENS_INDEX_PREFIX}_categories'
    networks:
      - local
  caddy:
    image: caddy:2.7.2-alpine
    volumes:
      - ./Caddyfile-ci:/etc/caddy/Caddyfile
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik'
      - 'traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${BASE_DOMAIN_NAME}.${CI_DOMAIN}`)'
      - 'traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls=false'
      - 'traefik.http.routers.${COMPOSE_PROJECT_NAME}.service=${COMPOSE_PROJECT_NAME}'
      - 'traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=80'
      - 'traefik.http.middlewares.${COMPOSE_PROJECT_NAME}_headers.headers.customrequestheaders.X-Forwarded-Proto=http'
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}_auth.basicauth.users=akretion:$$2y$$05$$d70MjPbv5JBIr3TAVEUXku0/RrY6jVb5atNshPNeRDrk7iSVZ16Py" # akretion/nobot
      - 'traefik.http.routers.${COMPOSE_PROJECT_NAME}.middlewares=${COMPOSE_PROJECT_NAME}_auth,${COMPOSE_PROJECT_NAME}_headers'
    networks:
      local:
      traefik:
networks:
  traefik:
    external: true
  local:
