services:
  nuxt:
    build:
      context: .
    image: '${BUILD_NAME}_nuxt'
    environment:
      NUXT_PUBLIC_SEARCH_URL: https://dev-typesense.akretion.com
      NUXT_PUBLIC_SEARCH_INDICES_COMPANIES_EN: '${TYPESENS_INDEX_PREFIX}_companies'
      NUXT_PUBLIC_SEARCH_INDICES_PERSONS_EN: '${TYPESENS_INDEX_PREFIX}_persons'
      NUXT_PUBLIC_SEARCH_INDICES_MODULES_EN: '${TYPESENS_INDEX_PREFIX}_modules'
      NUXT_PUBLIC_SEARCH_INDICES_CATEGORIES_EN: '${TYPESENS_INDEX_PREFIX}_categories'
    networks:
      - local
  caddy:
    image: caddy:2.7.2-alpine
    volumes:
      - ./Caddyfile-ci:/etc/caddy/Caddyfile
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik'
      - 'traefik.http.routers.${COMPOSE_PROJECT_NAME}_nuxt.rule=Host(`${BASE_DOMAIN_NAME}nuxt.${CI_DOMAIN}`)'
      - 'traefik.http.routers.${COMPOSE_PROJECT_NAME}_nuxt.tls=false'
      - 'traefik.http.routers.${COMPOSE_PROJECT_NAME}_nuxt.service=${COMPOSE_PROJECT_NAME}_nuxt'
      - 'traefik.http.services.${COMPOSE_PROJECT_NAME}_nuxt.loadbalancer.server.port=80'
      - 'traefik.http.routers.${COMPOSE_PROJECT_NAME}_nuxt.middlewares=${COMPOSE_PROJECT_NAME}_nuxt'
      - 'traefik.http.middlewares.${COMPOSE_PROJECT_NAME}_nuxt.headers.customrequestheaders.X-Forwarded-Proto=http'
    networks:
      local:
      traefik:
networks:
  traefik:
    external: true
  local:
