services:
  nuxt:
    restart: always
    image: registry.gitlab.akretion.com/shopinvader/oca-appstore:latest
    environment:
      NUXT_SHOPINVADER_TYPESENS_URL: https://dev-typesense.akretion.com
      NUXT_SHOPINVADER_TYPESENS_INDICES_OCASTORE_SPONSORS: ocastore_sponsors
      NUXT_SHOPINVADER_TYPESENS_INDICES_OCASTORE_PERSONS: ocastore_persons
      NUXT_SHOPINVADER_TYPESENS_INDICES_OCASTORE_MODULES: ocastore_modules
      NUXT_SHOPINVADER_TYPESENS_INDICES_OCASTORE_CATEGORIES: ocastore_categories
      NUXT_PUBLIC_SHOPINVADER_TYPESENS_URL: https://dev-typesense.akretion.com
      NUXT_PUBLIC_SHOPINVADER_TYPESENS_INDICES_SPONSORS: ocastore_sponsors
      NUXT_PUBLIC_SHOPINVADER_TYPESENS_INDICES_PERSONS: ocastore_persons
      NUXT_PUBLIC_SHOPINVADER_TYPESENS_INDICES_MODULES: ocastore_modules
      NUXT_PUBLIC_SHOPINVADER_TYPESENS_INDICES_CATEGORIES: ocastore_categories
    depends_on:
      - payload
    ports:
      - 3000:3000
    labels:
      - "docky.main.service=True"
      - "docky.user=ubuntu"
