sops:
    age:
        - recipient: age1el0a6427u0ggzey78n96achvmueyf5e3qhh5jjmpjgk4gfnnx46qd4fewg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpSUNqWEJ4VG43Z2YwN2li
            SVVyMkhqOWZxejM2MEI1aVZvSnUyOHhjSEVBCjlleDJZMlo4WUc1aDFsdWdzMGJp
            eEoyUGkwQjVRT3kyb3ZwSkRYQ2RKWU0KLS0tIHUvQXFTTFJJakJkZEMrNWlRTHBp
            MXhEQ2xuUm5TVkgvZXlwSlczU0ZNTVUKHIgrdFEm2jnwT26PeOrnHgddOW2PvYXa
            PLrwHmZCEJu7fDj81Ow+FVfrIDjHP7udE0rHV/jdYdP72tUv2tIxDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-19T11:52:21Z"
    mac: ENC[AES256_GCM,data:13ot2e2YXgMi9RTpdHXGPH0xXfxA+uaTxlGWNA/rVEwoSx1UmypbQg306+pbVXoPZKagQY8WsNP8ndH3jpFc9YLFzXcVJrftHQhP36KnbXLHntBV59LZb4Da9ydv5M0GdeWSa/xfL9S+UGcb9B9CYWxzhoU9Q6PUODoarcU9hak=,iv:WYj083Dic9NQIVqPchogFQuCV76jhbFCjLrq5usC8Lg=,tag:De19UllBsa1pyYaohWjTrw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
