# https://github.com/actions/deploy-pages#usage
name: Deploy to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - add-github-config
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: '24.11.1'
      # Pick your own package manager and build script
      - run: pnpm install
      - run: pnpx nuxt build --preset github_pages
        env:
          NUXT_APP_BASE_URL: /${{ github.event.repository.name }}
          NUXT_PUBLIC_SEARCH_URL: https://search.odoo-community.org
          NUXT_PUBLIC_SEARCH_KEY: NrQZ2N1jFKutefDt3idZ0sR9wfNiPHtQ
          NUXT_PUBLIC_SEARCH_INDICES_COMPANIES_EN: 'ocastore_companies_en_us'
          NUXT_PUBLIC_SEARCH_INDICES_PERSONS_EN: 'ocastore_persons_en_us'
          NUXT_PUBLIC_SEARCH_INDICES_MODULES_EN: 'ocastore_modules_en_us'
          NUXT_PUBLIC_SEARCH_INDICES_CATEGORIES_EN: 'ocastore_categories_en_us'
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.output/public
          keep_files: false
